Task1/Models/ErrorViewModel.cs
namespace Task1.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Task1/Controllers/AirbnbsController.cs
using Microsoft.AspNetCore.Mvc;

namespace Task1.Controllers
{
    public class AirbnbsController : Controller
    {
        public IActionResult Airbnbs()
        {
            return View();
        } 
        public IActionResult Detailes()
        {
            return View();
        }
    }
}

Task1/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Task1.Models;

namespace Task1.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Task1/Controllers/ToursController.cs
using Microsoft.AspNetCore.Mvc;

namespace Task1.Controllers
{
    public class ToursController : Controller
    {
        public IActionResult Tours()
        {
            return View();
        }

        public IActionResult Detailes()
        {
            return View();
        }

    }
}

Task1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Task1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Task1.styles.css" asp-append-version="true" />


	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="Panagea - Premium site template for travel agencies, hotels and restaurant listing.">
	<meta name="author" content="Ansonika">
	<title>Advenures DarNa</title>

	<!-- Favicons-->
	<link rel="shortcut icon" href="img/favicon.ico" type="image/x-icon">
	<link rel="apple-touch-icon" type="image/x-icon" href="img/apple-touch-icon-57x57-precomposed.png">
	<link rel="apple-touch-icon" type="image/x-icon" sizes="72x72" href="img/apple-touch-icon-72x72-precomposed.png">
	<link rel="apple-touch-icon" type="image/x-icon" sizes="114x114" href="img/apple-touch-icon-114x114-precomposed.png">
	<link rel="apple-touch-icon" type="image/x-icon" sizes="144x144" href="img/apple-touch-icon-144x144-precomposed.png">

	<!-- GOOGLE WEB FONT -->
	<link rel="preconnect" href="https://fonts.gstatic.com/">
	<link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700;800&amp;display=swap" rel="stylesheet">

	<!-- BASE CSS -->
	<link href="../css/bootstrap.min.css" rel="stylesheet">
	<link href="../css/style.css" rel="stylesheet">
	<link href="../css/vendors.css" rel="stylesheet">

	<!-- YOUR CUSTOM CSS -->
	<link href="../css/custom.css" rel="stylesheet">

	<!-- Modernizr -->
	<script src="../js/modernizr.js"></script>

	<!-- ALTERNATIVE COLORS CSS -->
	<link href="#" id="colors" rel="stylesheet">
</head>
<body>



    @* <header> *@
    @*     <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3"> *@
    @*         <div class="container-fluid"> *@
    @*             <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Task1</a> *@
    @*             <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent" *@
    @*                     aria-expanded="false" aria-label="Toggle navigation"> *@
    @*                 <span class="navbar-toggler-icon"></span> *@
    @*             </button> *@
    @*             <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between"> *@
    @*                 <ul class="navbar-nav flex-grow-1"> *@
    @*                     <li class="nav-item"> *@
    @*                         <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a> *@
    @*                     </li> *@
    @*                     <li class="nav-item"> *@
    @*                         <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a> *@
    @*                     </li> *@
    @*                 </ul> *@
    @*             </div> *@
    @*         </div> *@
    @*     </nav> *@
    @* </header> *@







    <header class="header menu_fixed">
        <div id="preloader">
            <div data-loader="circle-side"></div>
        </div><!-- /Preload -->
        <div id="logo">
            <a href="index-2.html">
                <img src="../img/DarNa دارنا.png" width="150" height="30" alt="" class="logo_normal">
                <img src="../img/DarNa دارنا.png" width="150" height="30" alt="" class="logo_sticky">
            </a>
        </div>
        <ul id="top_menu">
            <li><a href="cart-1.html" class="cart-menu-btn" title="Cart"></a></li>
            <li><a href="#sign-in-dialog" id="sign-in" class="login" title="Sign In">Sign In</a></li>
            <li><a href="wishlist.html" class="wishlist_bt_top" title="Your wishlist">Your wishlist</a></li>
        </ul>
        <!-- /top_menu -->
        <a href="#menu" class="btn_mobile">
            <div class="hamburger hamburger--spin" id="hamburger">
                <div class="hamburger-box">
                    <div class="hamburger-inner"></div>
                </div>
            </div>
        </a>
        <nav id="menu" class="main-menu">
            <ul>
                <li>
					<span><a asp-controller="Home" asp-action="Index">Home</a></span>

                </li>

                <li>
					<span><a asp-controller="Airbnbs" asp-action="Airbnbs">AirBnbs</a></span>

                </li>    
				<li>
					<span><a asp-controller="Airbnbs" asp-action="Detailes">AirBnbs Detailes</a></span>

                </li>

				<li><span><a asp-controller="Tours" asp-action="Tours">Tours & Adventures</a></span></li>
				<li><span><a asp-controller="Tours" asp-action="Detailes">Detailes</a></span>
          


            </ul>
        </nav>

    </header>


    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    @* <footer class="border-top footer text-muted"> *@
    @*     <div class="container"> *@
    @*         &copy; 2025 - Task1 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a> *@
    @*     </div> *@
    @* </footer> *@


	<footer>
		<div class="container margin_60_35">
			<div class="row">
				<div class="col-lg-5 col-md-12 pe-5">
					<p><img src="../img/DarNa دارنا.png" width="150" height="30" alt=""></p>
					<p>
						We’re dedicated to bridging the gap between travelers and the authentic beauty of Jordan. By
						offering a
						curated selection of Airbnb stays and hotels, we aim to provide a seamless booking
						experience that reflects the warmth and hospitality of Jordanian culture.
					</p>
					<div class="follow_us">
						<ul>
							<li>Follow us</li>
							<li><a href="#0"><i class="bi bi-facebook"></i></a></li>
							<li><a href="#0"><i class="bi bi-twitter-x"></i></a></li>
							<li><a href="#0"><i class="bi bi-instagram"></i></a></li>
							<li><a href="#0"><i class="bi bi-tiktok"></i></a></li>
							<li><a href="#0"><i class="bi bi-whatsapp"></i></a></li>
						</ul>
					</div>
				</div>
				<div class="col-lg-3 col-md-6 ms-lg-auto">
					<h5>Useful links</h5>
					<ul class="links">
						<li><a href="about.html">About</a></li>
						<li><a href="login.html">Login</a></li>
						<li><a href="register.html">Register</a></li>
						<li><a href="blog.html">News &amp; Events</a></li>
						<li><a href="contacts.html">Contacts</a></li>
					</ul>
				</div>
				<div class="col-lg-3 col-md-6">
					<h5>Contact with Us</h5>
					<ul class="contacts">
						<li><a href="tel://61280932400"><i class="ti-mobile"></i> +962 7 77 20 58 35 </a></li>
						<li>
							<a href="mailto:info@Panagea.com"><i class="ti-email"></i> hanijarrah20@gamil.com</a>
						</li>
					</ul>
					<div id="newsletter">
						<h6>Newsletter</h6>
						<div id="message-newsletter"></div>
						<form method="post"
							  action="https://www.ansonika.com/panagea/phpmailer/newsletter_template_email.php"
							  name="newsletter_form" id="newsletter_form">
							<div class="form-group">
								<input type="email" name="email_newsletter" id="email_newsletter"
									   class="form-control" placeholder="Your email">
								<input type="submit" value="Submit" id="submit-newsletter">
							</div>
						</form>
					</div>
				</div>
			</div>
			<!--/row-->
			<hr>
			<div class="row">
				<div class="col-lg-6">
					<ul id="footer-selector">
						<li>
							<div class="styled-select" id="lang-selector">
								<select>
									<option value="English" selected>English</option>
									<option value="French">Arabic</option>

								</select>
							</div>
						</li>
						<li>
							<div class="styled-select" id="currency-selector">
								<select>
									<option value="US Dollars">US Dollars</option>
									<option value="Euro" selected>Jor Dinar</option>
								</select>
							</div>
						</li>
						<li><img src="img/cards_all.svg" alt=""></li>
					</ul>
				</div>
				<div class="col-lg-6">
					<ul id="additional_links">
						<li><a href="#0">Terms and conditions</a></li>
						<li><a href="#0">Privacy</a></li>
						<li><span>© DarNa</span></li>
					</ul>
				</div>
			</div>
		</div>
	</footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)

	<div id="toTop"></div><!-- Back to top button -->
	<!-- COMMON SCRIPTS -->
	<script src="../js/common_scripts.js"></script>
	<script src="../js/main.js"></script>
	<script src="../phpmailer/validate.js"></script>

	<!-- SPECIFIC SCRIPTS -->
	<script src="../js/video_header.js"></script>
	<script>
		HeaderVideo.init({
			container: $('.header-video'),
			header: $('.header-video--media'),
			videoTrigger: $("#video-trigger"),
			autoPlayVideo: true
		});
	</script>
</body>
</html>